SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cars](
	[Id] [nvarchar](36) NOT NULL,
	[carName] [nvarchar](250) NOT NULL,
	[Brand] [nvarchar](15) NOT NULL,
	[licencePlate] [nvarchar](15) NOT NULL,
	[luggage] [nvarchar](250) NOT NULL,
	[passenger] [nvarchar](250) NOT NULL,
	[partners] [nvarchar](36) NOT NULL,
        [photoUrl] [nvarchar](MAX) NOT NULL,
	[isRegisterd] [bit] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[Cars] ADD PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[Cars] ADD UNIQUE NONCLUSTERED 
(
	[carName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cars] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[Cars] ADD  DEFAULT ((1)) FOR [isRegisterd]
GO
ALTER TABLE [dbo].[Cars]  WITH CHECK ADD  CONSTRAINT [FK_Partner_Car] FOREIGN KEY([partners])
REFERENCES [dbo].[Partners] ([Id])
GO
ALTER TABLE [dbo].[Cars] CHECK CONSTRAINT [FK_Partner_Car]
GO
